spring:
    oauth2:
      client:
        registration:
            google:
                clientId: <your-client-id>
                clientSecret: <your-client-secret>
                authorizationGrantType: authorization_code
                redirectUri: "http://localhost:8080/login/oauth/google"
                tokenUri: https://www.googleapis.com/oauth2/v4/token
                userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
                scope: email, profile
            naver:
                client-id: <your-client-id>
                client-secret: <your-client-secret>
                authorization-grant-type: authorization_code
                redirect-uri: "http://localhost:8080/login/oauth/naver"
                token-uri: https://nid.naver.com/oauth2.0/token
                user-info-uri: https://openapi.naver.com/v1/nid/me
                scope: name, email
            kakao:
                clientId: <your-client-id>
                clientSecret: <your-client-secret>
                authorizationGrantType: authorization_code
                redirectUri: "http://localhost:8080/login/oauth/kakao"
                tokenUri: https://kauth.kakao.com/oauth/token
                userInfoUri: https://kapi.kakao.com/v2/user/me
                scope: profile_nickname, profile_image

    mvc:
        static-path-pattern: /**
    web:
      resources:
          static-locations: classpath:/static/

